version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    container_name: todos_dev
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      - todos_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

  bravi_template:
    build:
      context: .
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    container_name: todos_app
    volumes:
      - .:/usr/src/application
    restart: unless-stopped
    ports:
      - "8001:8000"
    env_file:
      - .env
    networks:
      - todos_dev
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    depends_on:
      - db

  pgadmin:
    container_name: todos_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - todos_dev
    depends_on:
      - db

networks:
  todos_dev:
    external: true
    name: todos_dev

volumes:
  postgres_data:
